# Generated by Django 5.0.7 on 2024-09-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_detalleproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalleProducto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='porducto_detalle', to='inventario.detalleproducto'),
        ),
    ]
